/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PageImport } from './routes/_page'
import { Route as EditorImport } from './routes/_editor'
import { Route as PageIndexImport } from './routes/_page/index'
import { Route as PagePostsLatestImport } from './routes/_page/posts.latest'
import { Route as PagePostsIdImport } from './routes/_page/posts.$id'
import { Route as PagePostsUsersIdImport } from './routes/_page/posts.users.$id'
import { Route as PagePostsProductsIdImport } from './routes/_page/posts.products.$id'
import { Route as EditorEditPostIdImport } from './routes/_editor/edit.post.$id'

// Create/Update Routes

const PageRoute = PageImport.update({
  id: '/_page',
  getParentRoute: () => rootRoute,
} as any)

const EditorRoute = EditorImport.update({
  id: '/_editor',
  getParentRoute: () => rootRoute,
} as any)

const PageIndexRoute = PageIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PageRoute,
} as any)

const PagePostsLatestRoute = PagePostsLatestImport.update({
  id: '/posts/latest',
  path: '/posts/latest',
  getParentRoute: () => PageRoute,
} as any)

const PagePostsIdRoute = PagePostsIdImport.update({
  id: '/posts/$id',
  path: '/posts/$id',
  getParentRoute: () => PageRoute,
} as any)

const PagePostsUsersIdRoute = PagePostsUsersIdImport.update({
  id: '/posts/users/$id',
  path: '/posts/users/$id',
  getParentRoute: () => PageRoute,
} as any)

const PagePostsProductsIdRoute = PagePostsProductsIdImport.update({
  id: '/posts/products/$id',
  path: '/posts/products/$id',
  getParentRoute: () => PageRoute,
} as any)

const EditorEditPostIdRoute = EditorEditPostIdImport.update({
  id: '/edit/post/$id',
  path: '/edit/post/$id',
  getParentRoute: () => EditorRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_editor': {
      id: '/_editor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof EditorImport
      parentRoute: typeof rootRoute
    }
    '/_page': {
      id: '/_page'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PageImport
      parentRoute: typeof rootRoute
    }
    '/_page/': {
      id: '/_page/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageIndexImport
      parentRoute: typeof PageImport
    }
    '/_page/posts/$id': {
      id: '/_page/posts/$id'
      path: '/posts/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PagePostsIdImport
      parentRoute: typeof PageImport
    }
    '/_page/posts/latest': {
      id: '/_page/posts/latest'
      path: '/posts/latest'
      fullPath: '/posts/latest'
      preLoaderRoute: typeof PagePostsLatestImport
      parentRoute: typeof PageImport
    }
    '/_editor/edit/post/$id': {
      id: '/_editor/edit/post/$id'
      path: '/edit/post/$id'
      fullPath: '/edit/post/$id'
      preLoaderRoute: typeof EditorEditPostIdImport
      parentRoute: typeof EditorImport
    }
    '/_page/posts/products/$id': {
      id: '/_page/posts/products/$id'
      path: '/posts/products/$id'
      fullPath: '/posts/products/$id'
      preLoaderRoute: typeof PagePostsProductsIdImport
      parentRoute: typeof PageImport
    }
    '/_page/posts/users/$id': {
      id: '/_page/posts/users/$id'
      path: '/posts/users/$id'
      fullPath: '/posts/users/$id'
      preLoaderRoute: typeof PagePostsUsersIdImport
      parentRoute: typeof PageImport
    }
  }
}

// Create and export the route tree

interface EditorRouteChildren {
  EditorEditPostIdRoute: typeof EditorEditPostIdRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorEditPostIdRoute: EditorEditPostIdRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

interface PageRouteChildren {
  PageIndexRoute: typeof PageIndexRoute
  PagePostsIdRoute: typeof PagePostsIdRoute
  PagePostsLatestRoute: typeof PagePostsLatestRoute
  PagePostsProductsIdRoute: typeof PagePostsProductsIdRoute
  PagePostsUsersIdRoute: typeof PagePostsUsersIdRoute
}

const PageRouteChildren: PageRouteChildren = {
  PageIndexRoute: PageIndexRoute,
  PagePostsIdRoute: PagePostsIdRoute,
  PagePostsLatestRoute: PagePostsLatestRoute,
  PagePostsProductsIdRoute: PagePostsProductsIdRoute,
  PagePostsUsersIdRoute: PagePostsUsersIdRoute,
}

const PageRouteWithChildren = PageRoute._addFileChildren(PageRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PageRouteWithChildren
  '/': typeof PageIndexRoute
  '/posts/$id': typeof PagePostsIdRoute
  '/posts/latest': typeof PagePostsLatestRoute
  '/edit/post/$id': typeof EditorEditPostIdRoute
  '/posts/products/$id': typeof PagePostsProductsIdRoute
  '/posts/users/$id': typeof PagePostsUsersIdRoute
}

export interface FileRoutesByTo {
  '': typeof EditorRouteWithChildren
  '/': typeof PageIndexRoute
  '/posts/$id': typeof PagePostsIdRoute
  '/posts/latest': typeof PagePostsLatestRoute
  '/edit/post/$id': typeof EditorEditPostIdRoute
  '/posts/products/$id': typeof PagePostsProductsIdRoute
  '/posts/users/$id': typeof PagePostsUsersIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_editor': typeof EditorRouteWithChildren
  '/_page': typeof PageRouteWithChildren
  '/_page/': typeof PageIndexRoute
  '/_page/posts/$id': typeof PagePostsIdRoute
  '/_page/posts/latest': typeof PagePostsLatestRoute
  '/_editor/edit/post/$id': typeof EditorEditPostIdRoute
  '/_page/posts/products/$id': typeof PagePostsProductsIdRoute
  '/_page/posts/users/$id': typeof PagePostsUsersIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/'
    | '/posts/$id'
    | '/posts/latest'
    | '/edit/post/$id'
    | '/posts/products/$id'
    | '/posts/users/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/'
    | '/posts/$id'
    | '/posts/latest'
    | '/edit/post/$id'
    | '/posts/products/$id'
    | '/posts/users/$id'
  id:
    | '__root__'
    | '/_editor'
    | '/_page'
    | '/_page/'
    | '/_page/posts/$id'
    | '/_page/posts/latest'
    | '/_editor/edit/post/$id'
    | '/_page/posts/products/$id'
    | '/_page/posts/users/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  EditorRoute: typeof EditorRouteWithChildren
  PageRoute: typeof PageRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  EditorRoute: EditorRouteWithChildren,
  PageRoute: PageRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_editor",
        "/_page"
      ]
    },
    "/_editor": {
      "filePath": "_editor.tsx",
      "children": [
        "/_editor/edit/post/$id"
      ]
    },
    "/_page": {
      "filePath": "_page.tsx",
      "children": [
        "/_page/",
        "/_page/posts/$id",
        "/_page/posts/latest",
        "/_page/posts/products/$id",
        "/_page/posts/users/$id"
      ]
    },
    "/_page/": {
      "filePath": "_page/index.tsx",
      "parent": "/_page"
    },
    "/_page/posts/$id": {
      "filePath": "_page/posts.$id.tsx",
      "parent": "/_page"
    },
    "/_page/posts/latest": {
      "filePath": "_page/posts.latest.tsx",
      "parent": "/_page"
    },
    "/_editor/edit/post/$id": {
      "filePath": "_editor/edit.post.$id.tsx",
      "parent": "/_editor"
    },
    "/_page/posts/products/$id": {
      "filePath": "_page/posts.products.$id.tsx",
      "parent": "/_page"
    },
    "/_page/posts/users/$id": {
      "filePath": "_page/posts.users.$id.tsx",
      "parent": "/_page"
    }
  }
}
ROUTE_MANIFEST_END */
